const FRONTEND_VERSION = 'android-capture-v1';
const $ = id => document.getElementById(id); const state={result:null,analyzing:false}; const HLS_IMPORT_HOSTS=['surrit.com','nineyu.com']; let deferredInstallPrompt=null;
function setAnalyzing(a){state.analyzing=a;$('analyzeButton').disabled=a;$('pasteAnalyzeButton').disabled=a;$('analyzeButton').textContent=a?'분석 중…':'영상 찾기';$('pasteAnalyzeButton').textContent=a?'영상 찾는 중…':'복사한 영상 바로 찾기';$('status').classList.toggle('show',a);if(a){$('error').classList.remove('show');$('result').classList.remove('show')}}
function showError(m){$('error').textContent=m;$('error').classList.add('show');$('status').classList.remove('show')} function updateProgress(p,t,m){$('download').classList.add('show');const e=$('progressBar').parentElement;e.hidden=false;const n=Number(p);$('progressBar').style.width=Number.isFinite(n)?`${Math.max(0,Math.min(100,n))}%`:'0%';$('downloadPercent').textContent=typeof p==='number'?`${Math.round(p)}%`:String(p||'');$('downloadTitle').textContent=t;$('downloadMessage').textContent=m}
function isNjavUrl(v){try{const u=new URL(String(v||'').trim()),h=u.hostname.toLowerCase();return u.protocol==='https:'&&(h==='njavtv.com'||h==='www.njavtv.com')}catch{return false}} function extractPageUrl(v){const text=String(v||'').trim();if(!text)return null;for(const c of [text,...(text.match(/https:\/\/[^\s<>"']+/gi)||[])]){try{const u=new URL(c.replace(/[),.]+$/,''));if(isNjavUrl(u.href))return u.href}catch{}}return null}
function errorMessage(d,s){if(typeof d?.detail==='string')return d.detail;if(typeof d?.message==='string')return d.message;return `영상 분석에 실패했습니다. (${s||'network'})`} function showHelper(){$('helperPanel')?.removeAttribute('hidden')} function hideHelper(){$('helperPanel')?.setAttribute('hidden','')}
async function analyzeUrl(v,{source='manual'}={}){if(state.analyzing)return false;const url=extractPageUrl(v);if(!url){showError(source==='clipboard'?'복사한 내용에 NJAVTV 영상 주소가 없습니다.':'NJAVTV 영상 페이지 주소를 확인해 주세요.');return false}$('pageUrl').value=url;hideHelper();setAnalyzing(true);void window.warmDownloaderWorker?.().catch(()=>{});try{const r=await fetch('/api/video-resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(errorMessage(d,r.status));state.result=d;if(typeof window.renderResult!=='function')throw new Error('저장 화면을 준비하지 못했습니다.');window.renderResult(d);hideHelper();return true}catch(e){showError(e?.message||'영상 분석에 실패했습니다.');showHelper();return false}finally{setAnalyzing(false)}}
async function analyzeClipboard(){if(!window.isSecureContext||!navigator.clipboard?.readText){showError('자동 붙여넣기를 사용할 수 없습니다. 아래 주소 직접 입력을 사용해 주세요.');$('manualEntry')?.setAttribute('open','');return}try{const t=await navigator.clipboard.readText();if(!t.trim())throw new Error('empty');await analyzeUrl(t,{source:'clipboard'})}catch(e){showError(e?.message==='empty'?'복사된 주소가 없습니다. NJAVTV에서 링크 복사를 먼저 해주세요.':'클립보드 읽기가 허용되지 않았습니다. 아래 주소 직접 입력을 사용해 주세요.')}}
function sharedEntry(){const p=new URLSearchParams(location.search),c=[p.get('url'),p.get('text'),p.get('title')].filter(Boolean);if(!c.length)return false;history.replaceState(null,'',location.pathname+location.hash);for(const v of c){const u=extractPageUrl(v);if(u){void analyzeUrl(u,{source:'share'});return true}}showError('공유된 내용에서 NJAVTV 영상 주소를 찾지 못했습니다.');return true}
function installedMode(){return window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true} function updateInstallUi(){const i=installedMode(),card=$('installCard'),ready=$('shareReady');if(card)card.hidden=i;if(ready)ready.hidden=!i}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallUi()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallUi()});$('installAppButton')?.addEventListener('click',async()=>{if(!deferredInstallPrompt){const h=$('installHint');if(h)h.textContent='삼성 인터넷 메뉴에서 ‘현재 페이지 추가’ → ‘앱스 화면’을 선택해 주세요.';return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice.catch(()=>null);deferredInstallPrompt=null;updateInstallUi()});
function allowedImportedHls(v){try{const u=new URL(String(v||'').trim()),h=u.hostname.toLowerCase();if(u.protocol!=='https:'||!/\.m3u8$/i.test(u.pathname))return null;if(!HLS_IMPORT_HOSTS.some(s=>h===s||h.endsWith(`.${s}`)))return null;return u.href}catch{return null}} function importedQuality(v){return String(v).match(/\/(1920x1080|1280x720|842x480|640x360|1080p|720p|480p|360p)\//i)?.[1]||'자동'} function importedHeight(q){return {'1920x1080':1080,'1080p':1080,'1280x720':720,'720p':720,'842x480':480,'480p':480,'640x360':360,'360p':360}[q]||0} function importedVideoId(v){return String(v).match(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i)?.[1]||null}
function renderImportedStream({hls,source,title,resolver}){const quality=importedQuality(hls),page=extractPageUrl(source)||'';if(page)$('pageUrl').value=page;const result={ok:true,resolver,title:String(title||'NJAVTV 영상').trim().slice(0,180)||'NJAVTV 영상',videoId:importedVideoId(hls),pageUrl:page,streams:[{quality,height:importedHeight(quality),url:hls,available:true,manifestType:'hls'}]};state.result=result;if(typeof window.renderResult!=='function')throw new Error('저장 화면을 준비하지 못했습니다.');window.renderResult(result);hideHelper();return true}
function importAndroidCapture(){const p=new URLSearchParams(location.search);if(p.get('capture')!=='1')return false;const hls=allowedImportedHls(p.get('stream'));const source=String(p.get('page')||'').trim(),title=String(p.get('title')||'NJAVTV 영상').trim();history.replaceState(null,'',location.pathname+location.hash);if(!hls){showError('캡처한 영상 주소가 올바르지 않습니다. 영상 페이지에서 다시 공유해 주세요.');return true}renderImportedStream({hls,source,title,resolver:'android-capture-v1'});return true}
function browserHandoffCode(){const target=JSON.stringify(`${location.origin}${location.pathname}`);return `javascript:(()=>{let n=0;const abs=u=>{try{return new URL(u,location.href).href}catch{return''}};const find=()=>{let u=(window.hls&&window.hls.url)||'';if(!u){for(const v of document.querySelectorAll('video')){u=(v._hls&&v._hls.url)||((/\\.m3u8(?:\\?|$)/i.test(v.currentSrc||''))?v.currentSrc:'')||((/\\.m3u8(?:\\?|$)/i.test(v.src||''))?v.src:'');if(u)break}}if(!u){const a=performance.getEntriesByType('resource').map(e=>e.name).filter(x=>/\\.m3u8(?:\\?|$)/i.test(x));u=a[a.length-1]||''}u=abs(u);if(u){const p=new URLSearchParams({hls:u,title:document.title||'NJAVTV video',source:location.origin+location.pathname});location.href=${target}+'#'+p.toString();return}if(++n<12){setTimeout(find,1000);return}alert('영상 재생 버튼을 한 번 누른 뒤 다시 실행하세요.');};find()})()`}
function importBrowserHandoff(){if(!location.hash||location.hash.length<2)return false;const p=new URLSearchParams(location.hash.slice(1)),hls=allowedImportedHls(p.get('hls'));if(!hls)return false;const source=String(p.get('source')||'').trim(),title=String(p.get('title')||'NJAVTV 영상').trim().slice(0,180)||'NJAVTV 영상';renderImportedStream({hls,source,title,resolver:'browser-handoff-v2'});history.replaceState(null,'',location.pathname+location.search);return true}
$('analyzeForm').addEventListener('submit',e=>{e.preventDefault();void analyzeUrl($('pageUrl').value)});$('pasteAnalyzeButton').addEventListener('click',()=>void analyzeClipboard());$('copyHelper')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(browserHandoffCode());$('copyHelper').textContent='복사됨'}catch{showError('고급 추출 코드를 복사하지 못했습니다.')}});
async function enablePwa(){if(!('serviceWorker'in navigator))return;try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller&&typeof sessionStorage!=='undefined'&&!sessionStorage.getItem('pwa-reload-v3')){sessionStorage.setItem('pwa-reload-v3','1');location.reload()}}catch{}}
window.addEventListener('DOMContentLoaded',()=>{updateInstallUi();try{if(importAndroidCapture())return;if(importBrowserHandoff())return;sharedEntry()}catch(e){showError(e?.message||'공유된 영상 주소를 처리하지 못했습니다.')}void enablePwa()});window.addEventListener('pageshow',()=>void window.warmDownloaderWorker?.().catch(()=>{}));
